version: "3"
services:
  postgres:
    image: postgres:alpine
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      POSTGRES_USER: accounts
      POSTGRES_PASSWORD: accounts
      POSTGRES_DB: accounts
