version: "3"
services:
  redis:
    image: redis:alpine
    ports:
      - "127.0.0.1:6379:6379"
  postgres:
    image: postgres:alpine
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - ./ci/create_db.sql:/docker-entrypoint-initdb.d/10_create_db.sql
    environment:
      POSTGRES_USER: accounts
      POSTGRES_PASSWORD: accounts
      POSTGRES_DB: postgres